
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target "MGProgressHUD" do

pod 'MBProgressHUD', '~> 1.1.0'


pod 'Masonry', '~> 1.1.0'

pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'


pod 'Color-Picker-for-iOS', '~> 2.0'






end
